define boss = Character('Босс', color="#e71616")
define me = Character('Я', color="#9100f1")
define unknown = Character('Незнакомка', color="#c8ffc8")
define yulia = Character('Юлечка', color="#FF69B4")
define father = Character('Батя', color="#008000")
define evil = Character('Тамара', color="#800080")
define zina = Character('Зина', color="#ff8f00")
define racoon_queen = Character('Королева Енотов', color="#1e8036")
define reporter = Character('Посетитель книжного магазина', color="#f0d806")
define crab_queen = Character('Королева крабов', color="#fa0000")
define unknown_phone = Character('Незнакомец', color="#fa0000")
define raccoon = Character('Енотик', color="#fa9600")
define glasha = Character('Глаша', color="#7500fa")