#Фоны
image glasha_room = "images/Backgrounds/GlashaRoom.jpg"
image father_room = "images/Backgrounds/FatherRoom.jpg"
image red_room = "images/Backgrounds/RedRoom.jpg"
image city = "images/Backgrounds/City.jpg"
image office = "images/Backgrounds/GlashaOffice.jpg"
image boss_office = "images/Backgrounds/BossOffice.jpg"
image yulia_room = "images/Backgrounds/YuliaRoom.jpg"
image intermedia = "images/Backgrounds/StarSky.jpg"
image book_store = "images/Backgrounds/BookStore.jpg"
image night_city = "images/Backgrounds/NightStreet.jpg"
image night_kiss = "images/Backgrounds/NightKiss.jpg"
image boss_room = "images/Backgrounds/BossRoom.jpg"
image white_room = "images/Backgrounds/WhiteRoom.png"
image crab_room = "images/Backgrounds/CrabRoom.png"
#Персонажи
image Boss = "images/Characters/Boss.png"
image Yulia = "images/Characters/Julia.png"
image Father = "images/Characters/Father.png"
image Tamara = "images/Characters/BadGirl.png"
image Zina = "images/Characters/Zina.png"
image RacoonQueen = "images/Characters/RacoonQueen.png"
image CrabQueen = "images/Characters/CrabQueen.png"